# Generated by Django 5.2.6 on 2025-09-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('WRITER', 'Writer'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=10),
        ),
    ]
