# Generated by Django 5.2.6 on 2025-09-24 09:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='writer_profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
