# Generated by Django 5.2.6 on 2025-09-25 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_writer_writer_profile_pic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='writer',
            field=models.ForeignKey(limit_choices_to={'role_in': ['WRITER', 'EDITOR', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
