# Generated by Django 5.2.6 on 2025-09-25 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_alter_newsarticle_writer_delete_writer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='writer',
            field=models.ForeignKey(limit_choices_to={'role': ['WRITER', 'EDITOR', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
